#! /bin/bash
# hppmerge
python3 -B cpp-library/scripts/merge.py

# prepremake
python3 -B cpp-library/scripts/prepremake.py &&
# premake
premake5 gmake --file="build/premake5.lua" && premake5 vs2022 --file="build/premake5.lua" &&
# make
make -C build config=debug && make -C build config=release && make -C build config=dist &&
# success
echo "** build successfull **"